export const CONTRACT_TERMS = [
  {
    title: "Payment",
    text:
      "Payment is due in full immediately upon substantial completion of the work described in this Agreement, unless an alternative payment schedule is stated in writing. Any deposit shown will be credited toward the total contract price.",
  },
  {
    title: "Changes and additional work",
    text:
      "Work outside the written scope requires customer approval and may result in additional charges.",
  },
  {
    title: "Cancellation",
    text:
      "The Customer may cancel this Agreement before crews, equipment, or subcontractors begin mobilization or work at the property. Once mobilization or work has begun, the Agreement may not be cancelled without payment for work performed, labor committed, materials purchased, equipment mobilization, disposal expenses, and other costs incurred by Valid Tree Service LLC.",
  },
  {
    title: "Underground and concealed conditions",
    text:
      "Before excavation, stump grinding, root removal, or other ground-disturbing work, the Customer is responsible for identifying and marking privately owned or unregistered underground facilities, including irrigation systems, landscape lighting, private electrical lines, drainage systems, septic components, pool lines, and similar improvements not located through the public utility-marking service. Valid Tree Service LLC is not responsible for damage to undisclosed or improperly marked private facilities, except to the extent prohibited by law.",
  },
  {
    title: "Access and authority",
    text:
      "The Customer confirms they are authorized to approve the work and will provide reasonable access for crews and equipment.",
  },
  {
    title: "Weather and safety",
    text:
      "Work may be delayed or rescheduled when weather, site conditions, utility conflicts, or other hazards make performance unsafe or impractical.",
  },
  {
    title: "Cleanup",
    text:
      "Debris generated by the agreed work will be removed and the immediate work area left reasonably clean unless otherwise stated in the scope.",
  },
  {
    title: "Tree condition and warranty",
    text:
      "Valid Tree Service LLC will perform the agreed work using reasonable care and professional tree-service practices. No guarantee is made regarding the future health, growth, stability, or survival of any tree, stump, root system, lawn, or landscaping unless a specific written warranty is included in this Agreement.",
  },
  {
    title: "Acceptance",
    text:
      "By signing, the Customer accepts the scope, price, payment terms, and conditions of this Agreement.",
  },
];

export const CONTRACTOR_NAME = "Mark Guerrero";
export const CONTRACTOR_TITLE = "Owner / Authorized Representative";
