const payment = { title: 'Payment', text: 'Payment is due in full immediately upon substantial completion of the work described in this Agreement, unless an alternative payment schedule is stated in writing. Any deposit shown will be credited toward the total contract price.' }
const acceptance = { title: 'Acceptance', text: 'By signing, the Customer accepts the scope, price, payment terms, and conditions of this Agreement.' }

export const CONTRACT_TYPES = {
  tree_service: {
    key: 'tree_service', label: 'Tree Service', numberPrefix: 'VTS',
    description: 'Removal, trimming, stump grinding, and related tree work.',
    agreementLabel: 'Professional Tree Care Agreement', defaultTitle: 'Tree Service Agreement', priceLabel: 'Agreed tree-service work',
    terms: [
      payment,
      { title: 'Changes and additional work', text: 'Work outside the written scope requires customer approval and may result in additional charges.' },
      { title: 'Cancellation', text: 'The Customer may cancel this Agreement before crews, equipment, or subcontractors begin mobilization or work at the property. Once mobilization or work has begun, the Agreement may not be cancelled without payment for work performed, labor committed, materials purchased, equipment mobilization, disposal expenses, and other costs incurred by Valid Tree Service LLC.' },
      { title: 'Underground and concealed conditions', text: 'Before excavation, stump grinding, root removal, or other ground-disturbing work, the Customer is responsible for identifying and marking privately owned or unregistered underground facilities, including irrigation systems, landscape lighting, private electrical lines, drainage systems, septic components, pool lines, and similar improvements not located through the public utility-marking service. Valid Tree Service LLC is not responsible for damage to undisclosed or improperly marked private facilities, except to the extent prohibited by law.' },
      { title: 'Access and authority', text: 'The Customer confirms they are authorized to approve the work and will provide reasonable access for crews and equipment.' },
      { title: 'Weather and safety', text: 'Work may be delayed or rescheduled when weather, site conditions, utility conflicts, or other hazards make performance unsafe or impractical.' },
      { title: 'Cleanup', text: 'Debris generated by the agreed tree work will be removed and the immediate work area left reasonably clean unless otherwise stated in the scope. Stump grindings, wood chips, and the soil-and-wood mixture produced by stump grinding remain on the property unless removal is specifically included in the written scope for an additional charge.' },
      { title: 'Tree condition and warranty', text: 'Valid Tree Service LLC will perform the agreed work using reasonable care and professional tree-service practices. No guarantee is made regarding the future health, growth, stability, or survival of any tree, stump, root system, lawn, or landscaping unless a specific written warranty is included in this Agreement.' },
      acceptance,
    ],
  },
  junk_removal: {
    key: 'junk_removal', label: 'Junk Removal', numberPrefix: 'VJR',
    description: 'Pickup, loading, hauling, and lawful disposal of listed items.',
    agreementLabel: 'Junk Removal Service Agreement', defaultTitle: 'Junk Removal Agreement', priceLabel: 'Agreed junk-removal services',
    terms: [
      payment,
      { title: 'Written scope and additional items', text: 'The price covers only the items, volume, weight, labor, access conditions, and services described in the written scope. Additional items, unexpected weight, extra trips, stairs, dismantling, or access limitations require Customer approval and may result in additional charges.' },
      { title: 'Ownership and authority', text: 'The Customer confirms they own the materials being removed or have permission from the owner to authorize their removal and disposal. The Customer is responsible for claims arising from items they were not authorized to discard.' },
      { title: 'Excluded and regulated materials', text: 'Hazardous, toxic, flammable, explosive, biomedical, radioactive, asbestos-containing, or otherwise regulated materials are excluded unless specifically identified and accepted in writing. This includes unknown liquids, fuels, chemicals, paint, pesticides, ammunition, compressed cylinders, medical waste, and similar materials. Work may stop if such materials are discovered.' },
      { title: 'Personal and valuable property', text: 'Before work begins, the Customer must remove cash, jewelry, documents, medication, electronics containing important data, keepsakes, and any item not intended for disposal. Items placed in or immediately beside the agreed removal area may be treated as approved for removal.' },
      { title: 'Access and site conditions', text: 'The Customer will provide safe, lawful, and reasonable access to the items. The Customer must disclose fragile surfaces, private utilities, access restrictions, pests, bodily fluids, sharp objects, structural hazards, or other unsafe conditions before work begins.' },
      { title: 'Disposal, donation, and recycling', text: 'Valid Tree Service LLC may choose lawful disposal, recycling, or donation methods. No promise is made that any particular item will be donated, recycled, resold, or returned after it has been loaded for removal.' },
      { title: 'Cancellation and mobilization', text: 'The Customer may cancel before crews or equipment begin mobilization. After mobilization or work begins, the Customer is responsible for labor, travel, loading, equipment, disposal fees, and other costs already incurred.' },
      { title: 'Cleanup', text: 'The immediate removal area will be left reasonably broom-clean when practical. Deep cleaning, repairs, removal of stains or residue, and work outside the written scope are not included.' },
      acceptance,
    ],
  },
  demolition: {
    key: 'demolition', label: 'Demolition', numberPrefix: 'VDM',
    description: 'Selective or complete demolition, debris removal, and cleanup.',
    agreementLabel: 'Demolition Service Agreement', defaultTitle: 'Demolition Agreement', priceLabel: 'Agreed demolition services',
    terms: [
      payment,
      { title: 'Written scope and change orders', text: 'Only the demolition, removal, hauling, and site work specifically described in the written scope are included. Changes, additional demolition, unexpected quantities, or work requested after signing require Customer approval and may result in additional charges.' },
      { title: 'Ownership, approvals, and permits', text: 'The Customer confirms they own the property or are authorized by the owner to approve the work. Responsibility for permits, approvals, engineering, surveys, and association or landlord authorization will be as stated in the written scope. The Customer must disclose all known restrictions before work begins.' },
      { title: 'Utilities and private lines', text: 'The Customer must identify all private or unregistered utilities and confirm required utility disconnections before demolition begins. Work may be delayed until electric, gas, water, communications, septic, irrigation, pool, and other affected systems are safely located, protected, or disconnected.' },
      { title: 'Hazardous materials', text: 'Testing, abatement, handling, and disposal of asbestos, lead, mold, contaminated soil, chemicals, fuel, refrigerants, biomedical waste, and other hazardous or regulated materials are excluded unless specifically included in writing. Work may stop if suspected hazardous materials are discovered.' },
      { title: 'Concealed and unknown conditions', text: 'Pricing is based on reasonably observable conditions. Hidden structural components, buried concrete, unknown foundations, inaccessible materials, pests, contamination, undocumented utilities, or other concealed conditions may require a written change in scope, price, or schedule.' },
      { title: 'Adjacent property and site protection', text: 'Reasonable care will be used around structures, pavement, landscaping, fences, and neighboring property. The Customer must identify especially fragile or protected areas. Demolition inherently involves vibration, dust, noise, and ground disturbance, and restoration is included only when stated in the written scope.' },
      { title: 'Access and safety', text: 'The Customer will provide safe and lawful equipment access and keep occupants, children, pets, vehicles, and unauthorized persons outside the work zone. Work may be suspended when site, weather, structural, utility, or other conditions make performance unsafe or impractical.' },
      { title: 'Debris and salvage', text: 'Demolition debris will be removed as stated in the scope. Materials are not reserved for the Customer unless identified in writing before work begins. Disposal, recycling, and salvage methods may be selected by Valid Tree Service LLC in compliance with applicable requirements.' },
      { title: 'Cancellation and mobilization', text: 'The Customer may cancel before crews, equipment, or subcontractors begin mobilization. After mobilization or work begins, the Customer is responsible for work performed, labor committed, equipment, subcontractors, disposal charges, materials, and other costs incurred.' },
      acceptance,
    ],
  },
}

export const normalizeContractType = (value) => Object.prototype.hasOwnProperty.call(CONTRACT_TYPES, value) ? value : 'tree_service'
export const getContractTypeDefinition = (value) => CONTRACT_TYPES[normalizeContractType(value)]
export const getContractTerms = (value) => getContractTypeDefinition(value).terms
export const CONTRACT_TERMS = CONTRACT_TYPES.tree_service.terms
export const CONTRACTOR_NAME = 'Mark Guerrero'
export const CONTRACTOR_TITLE = 'Owner / Authorized Representative'
