import { useMemo, useState } from 'react'
import { useWorkspace } from '../data/WorkspaceProvider'
import { calculateLandClearing, jobFinancials, money } from '../lib/operations'
import { Field, Metric, PageHeader } from '../components/OperationsUI'

const initial = { name: 'Magnolia land clearing', acres: 11, density: 'medium', timber_type: 'pine', average_diameter: 12, stump_removal: true, finish_grade: true, customer_equipment: true, crew_size: 4, labor_rate: 350, equipment_daily: 0, fuel_daily: 700, rental_total: 0, disposal_total: 0, contingency_percent: 15, overhead_percent: 15, target_margin_percent: 30 }
export default function EstimatorPage() {
  const ws = useWorkspace()
  const [form, setForm] = useState(initial)
  const result = useMemo(() => calculateLandClearing(form), [form])
  const historical = ws.data.jobs.filter((job) => job.status === 'completed' || job.completion_percent >= 100).map((job) => ({ job, f: jobFinancials(job, ws.data) }))
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  return <div className="operations-page"><PageHeader eyebrow="Production-based pricing" title="Land Clearing Estimator"><button className="button primary" onClick={() => ws.addAndWait('estimator_scenarios', { ...form, work_days: result.workDays, direct_cost: result.directCost, recommended_price: result.recommendedPrice, project_type: 'land_clearing', assumptions: { note: 'Planning model; verify with site walk and rental quotes.' } })}>Save scenario</button></PageHeader>
    <div className="estimator-layout"><section className="panel"><h2>Project assumptions</h2><div className="form-grid">
      <Field label="Scenario name" className="wide"><input value={form.name} onChange={(e) => set('name', e.target.value)} /></Field>
      <Field label="Acres"><input min="0" step=".1" type="number" value={form.acres} onChange={(e) => set('acres', e.target.value)} /></Field><Field label="Density"><select value={form.density} onChange={(e) => set('density', e.target.value)}>{['light','medium','heavy','extreme'].map((x) => <option key={x}>{x}</option>)}</select></Field>
      <Field label="Timber"><select value={form.timber_type} onChange={(e) => set('timber_type', e.target.value)}>{['pine','mixed','hardwood','brush'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Average diameter (in.)"><input min="0" type="number" value={form.average_diameter} onChange={(e) => set('average_diameter', e.target.value)} /></Field>
      <Field label="Crew size"><input min="1" type="number" value={form.crew_size} onChange={(e) => set('crew_size', e.target.value)} /></Field><Field label="Labor / person / day"><input min="0" type="number" value={form.labor_rate} onChange={(e) => set('labor_rate', e.target.value)} /></Field>
      <Field label="Equipment / day"><input min="0" type="number" value={form.equipment_daily} onChange={(e) => set('equipment_daily', e.target.value)} /></Field><Field label="Fuel / day"><input min="0" type="number" value={form.fuel_daily} onChange={(e) => set('fuel_daily', e.target.value)} /></Field>
      <Field label="Rental total"><input min="0" type="number" value={form.rental_total} onChange={(e) => set('rental_total', e.target.value)} /></Field><Field label="Disposal total"><input min="0" type="number" value={form.disposal_total} onChange={(e) => set('disposal_total', e.target.value)} /></Field>
      <Field label="Contingency %"><input min="0" max="100" type="number" value={form.contingency_percent} onChange={(e) => set('contingency_percent', e.target.value)} /></Field><Field label="Overhead %"><input min="0" max="100" type="number" value={form.overhead_percent} onChange={(e) => set('overhead_percent', e.target.value)} /></Field>
      <Field label="Target margin %"><input min="0" max="95" type="number" value={form.target_margin_percent} onChange={(e) => set('target_margin_percent', e.target.value)} /></Field>
      <div className="checks wide"><label><input type="checkbox" checked={form.stump_removal} onChange={(e) => set('stump_removal', e.target.checked)} /> Remove stumps</label><label><input type="checkbox" checked={form.finish_grade} onChange={(e) => set('finish_grade', e.target.checked)} /> Rough/final grading</label><label><input type="checkbox" checked={form.customer_equipment} onChange={(e) => set('customer_equipment', e.target.checked)} /> Customer provides major equipment</label></div>
    </div></section>
    <aside><section className="metric-grid two"><Metric label="Estimated work days" value={result.workDays.toFixed(1)} /><Metric label="Direct cost" value={money(result.directCost)} /><Metric label="Cost + risk + overhead" value={money(result.costWithOverhead)} /><Metric label="Recommended quote" value={money(result.recommendedPrice)} tone="success" note={`${money(result.perAcre)} per acre`} /></section><div className="notice"><strong>Bid safeguard</strong><p>This planning model is not a substitute for a site walk, production test, rental quote, utility locate, soil review, or written definition of the finished grade. Use unit-rate overrun clauses on uncertain work.</p></div></aside></div>
    <section className="panel"><h2>Historical job comparison</h2>{historical.length ? <div className="data-table"><div className="table-head"><span>Job</span><span>Acres</span><span>Revenue</span><span>Cost</span><span>Margin</span></div>{historical.map(({ job, f }) => <div className="table-row" key={job.id}><span><strong>{job.title}</strong><small>{job.number}</small></span><span>{job.acres || '—'}</span><span>{money(f.revenue)}</span><span>{money(f.actualCost)}</span><span>{f.margin.toFixed(1)}%</span></div>)}</div> : <p className="muted">Completed jobs will appear here once actual costs and production are recorded.</p>}</section>
  </div>
}
