import { loadCompanySettings } from './companySettings'
import { CONTRACT_TERMS, CONTRACTOR_NAME, CONTRACTOR_TITLE } from './contractTerms'

const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;')
const money = (value) => Number(value || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' })
const date = (value, fallback = 'To be scheduled') => { if (!value) return fallback; const parsed = new Date(String(value).includes('T') ? value : `${value}T12:00:00`); return Number.isNaN(parsed.getTime()) ? String(value) : parsed.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) }
const safeImage = (value) => String(value || '').trim().startsWith('data:image/') ? String(value).trim() : ''

export function printContract(contract) {
  const company = { ...loadCompanySettings(), ...(contract.settings || {}) }
  const customer = contract.customers || contract.customer || {}
  const balance = Math.max(Number(contract.total_price || 0) - Number(contract.deposit || 0), 0)
  const customerSignature = safeImage(contract.signature_data)
  const contractorName = contract.contractor_name || CONTRACTOR_NAME
  const contractorTitle = contract.contractor_title || CONTRACTOR_TITLE
  const contractorDate = contract.contractor_signed_at || contract.created_at || new Date().toISOString()
  const scopeItems = String(contract.scope_of_work || '').split('\n').map((item) => item.trim()).filter(Boolean).map((item) => `<li>${escapeHtml(item.replace(/^[-•]\s*/, ''))}</li>`).join('')
  const terms = CONTRACT_TERMS.map((term, index) => `<p><strong>${index + 1}. ${escapeHtml(term.title)}.</strong> ${escapeHtml(term.text)}</p>`).join('')
  const signatureBlock = customerSignature ? `<img class="signature-image" src="${customerSignature}" alt="Customer electronic signature">` : '<div class="signature-space"></div>'

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(contract.contract_number)} - Contract</title><style>
  @page{size:Letter;margin:.42in}*{box-sizing:border-box}body{margin:0;color:#172018;font-family:Arial,Helvetica,sans-serif;background:#fff}.document{max-width:8.5in;margin:auto}.header{display:flex;justify-content:space-between;align-items:center;gap:24px;padding:18px 22px;background:#11261a;color:#fff;border-radius:12px 12px 0 0}.logo{width:130px;max-height:78px;object-fit:contain}.company{text-align:right;font-size:11px;line-height:1.55}.company strong{display:block;font-size:17px}.accent{height:7px;background:#82ad45}.title-row{display:flex;justify-content:space-between;gap:20px;padding:22px 4px 14px;border-bottom:2px solid #d9e1d8}h1{margin:0;font-size:26px;color:#11261a}.number{text-align:right;font-size:11px;color:#526052}.number strong{display:block;color:#172018;font-size:15px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:16px 0}.box{border:1px solid #d7dfd6;border-radius:8px;padding:12px}.label{margin:0 0 6px;color:#667266;font-size:9px;font-weight:bold;letter-spacing:.12em;text-transform:uppercase}.box p{margin:3px 0;font-size:12px;line-height:1.4}h2{margin:17px 0 8px;color:#11261a;font-size:14px;letter-spacing:.05em;text-transform:uppercase}.scope{min-height:90px;border:1px solid #d7dfd6;border-radius:8px;padding:12px 16px}.scope ul{margin:0;padding-left:20px}.scope li{margin:0 0 6px;font-size:12px;line-height:1.4}.pricing{width:100%;border-collapse:collapse}.pricing td{padding:8px 11px;border-bottom:1px solid #dfe5de;font-size:12px}.pricing td:last-child{text-align:right;font-weight:bold}.pricing .total td{background:#eff5eb;font-size:15px;border:0}.terms{columns:2;column-gap:25px;font-size:8.7px;line-height:1.38;color:#3e493f}.terms p{break-inside:avoid;margin:0 0 7px}.terms strong{color:#172018}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:30px;margin-top:24px;break-inside:avoid;page-break-inside:avoid}.signature-space,.signature-image,.typed-signature{display:block;width:100%;height:65px;border-bottom:1px solid #172018}.signature-image{object-fit:contain;object-position:left bottom;background:#fff}.typed-signature{display:flex;align-items:flex-end;padding:0 4px 7px;font-family:"Segoe Script","Brush Script MT",cursive;font-size:24px}.signature-meta{display:flex;justify-content:space-between;gap:8px;margin-top:4px;color:#5e695f;font-size:8px}.printed{min-height:27px;padding:8px 2px 3px;border-bottom:1px solid #172018;font-size:10px}.signed-note{font-size:8px;color:#657067}.footer{margin-top:20px;padding-top:8px;border-top:1px solid #d7dfd6;text-align:center;color:#677268;font-size:8px}.no-print{position:fixed;right:18px;top:18px;padding:11px 16px;border:0;border-radius:8px;background:#82ad45;color:#0b160d;font-weight:bold;cursor:pointer}@media print{.no-print{display:none}.document{max-width:none}.signature-image{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
  </style></head><body><button class="no-print" onclick="window.print()">Print / Save PDF</button><main class="document">
  <header class="header"><img class="logo" src="${window.location.origin}/valid-tree-logo.png" alt="Valid Tree Service logo"><div class="company"><strong>${escapeHtml(company.legalName || 'Valid Tree Service LLC')}</strong>${escapeHtml(company.address || '')}<br>${escapeHtml(company.phone || '832-445-6535')} · ${escapeHtml(company.email || '')}<br>${escapeHtml(company.website || '')}</div></header><div class="accent"></div>
  <section class="title-row"><div><p class="label">Professional Tree Care Agreement</p><h1>${escapeHtml(contract.title || 'Tree Service Contract')}</h1></div><div class="number">Contract Number<strong>${escapeHtml(contract.contract_number)}</strong>Contract Date: ${date(contract.created_at, 'Today')}</div></section>
  <section class="grid"><div class="box"><p class="label">Customer</p><p><strong>${escapeHtml(customer.full_name || 'Customer')}</strong></p><p>${escapeHtml(customer.service_address || 'Service address not provided')}</p><p>${escapeHtml(customer.phone || '')}${customer.phone && customer.email ? ' · ' : ''}${escapeHtml(customer.email || '')}</p></div><div class="box"><p class="label">Project</p><p><strong>Scheduled service:</strong> ${date(contract.service_date)}</p><p><strong>Payment:</strong> Due upon completion</p><p><strong>Status:</strong> ${escapeHtml(customerSignature ? 'signed' : contract.status || 'draft')}</p></div></section>
  <h2>Scope of Work</h2><section class="scope"><ul>${scopeItems || '<li>Scope of work to be added.</li>'}</ul></section><h2>Contract Price</h2><table class="pricing"><tr><td>Agreed tree-service work</td><td>${money(contract.total_price)}</td></tr><tr><td>Deposit / advance payment</td><td>${money(contract.deposit)}</td></tr><tr class="total"><td>Balance due upon completion</td><td>${money(balance)}</td></tr></table><h2>Terms and Conditions</h2><section class="terms">${terms}</section>
  <section class="signatures"><div>${signatureBlock}<div class="signature-meta"><span>Customer Signature</span><span>${contract.signed_at ? date(contract.signed_at) : 'Date'}</span></div><div class="printed">${customerSignature ? escapeHtml(contract.signature_name || customer.full_name || '') : ''}</div><div class="signature-meta"><span>Printed Name</span></div>${contract.signed_at ? `<p class="signed-note">Electronically signed ${escapeHtml(new Date(contract.signed_at).toLocaleString('en-US'))}${contract.signer_email ? ` · ${escapeHtml(contract.signer_email)}` : ''}</p>` : ''}</div><div><div class="typed-signature">${escapeHtml(contractorName)}</div><div class="signature-meta"><span>Valid Tree Service LLC Representative</span><span>${date(contractorDate)}</span></div><div class="printed">${escapeHtml(contractorName)} · ${escapeHtml(contractorTitle)}</div><div class="signature-meta"><span>Printed Name / Title</span></div><p class="signed-note">Contractor acceptance applied when this agreement was generated.</p></div></section>
  <footer class="footer">${escapeHtml(company.legalName || 'Valid Tree Service LLC')} · ${escapeHtml(company.phone || '832-445-6535')} · ${escapeHtml(company.website || '')} · ${escapeHtml(company.tagline || 'Safety. Precision. Clean Results.')}</footer></main>
  <script>async function ready(){await Promise.all(Array.from(document.images).map(function(image){if(image.complete&&image.naturalWidth)return image.decode?image.decode().catch(function(){}):Promise.resolve();return new Promise(function(resolve){image.addEventListener('load',resolve,{once:true});image.addEventListener('error',resolve,{once:true});setTimeout(resolve,4000)})}));requestAnimationFrame(function(){requestAnimationFrame(function(){window.print()})})}window.addEventListener('load',ready)</script></body></html>`
  const popup = window.open('', '_blank')
  if (!popup) throw new Error('Your browser blocked the PDF window. Allow popups for this site and try again.')
  popup.opener = null; popup.document.open(); popup.document.write(html); popup.document.close()
}
